#!/bin/bash

# Delete old user preferences if they exist
PREFSFILE=/private/var/mobile/Library/Preferences/com.sticktron.darkmessages.plist
if [[ -f "$PREFSFILE" ]]; then
    rm -f $PREFSFILE
    echo "Removed old prefs"
fi

exit 0
